### ISSUE TITLE
Should not be able to sync "up" more than 5 minutes

### ISSUE THREAD

**Issue by spikyjt** [spikyjt/SailingTimer#15]
When pressing the UP button, to sync to the nearest minute before, you can increase the time to more than the starting time. This should not be possible.

**Comment by duckpaint** [comment]
There has to be an automatic sync, to the nearest minute. If the countdown is in 3:29, when pressed it syncs to 3:00 and if it is in 3:31, it syncs to 4.

**Comment by spikyjt** [comment]
> There has to be an automatic sync, to the nearest minute

No there doesn't! The up button syncs up and the down or back buttons sync down. Most dedicated sailing watches only sync down. I think being able to sync up is an improvement, but I want it to be predictable. The button you press does exactly what you expect it to.
