### ISSUE TITLE
Add support for Forerunner 235

### ISSUE THREAD

**Issue by spikyjt** [spikyjt/SailingTimer#9]

**Comment by laleclercq** [comment]
Hi, would it be possible to also add support for the forerunner 235? Thanks!! (some great reviews for other watches)

**Comment by laleclercq** [comment]
Or is there a way to do this myself?

**Comment by dantre7** [comment]
Hi, I too would love to see this on the 235! Looks like a great app, good effort!

**Comment by spikyjt** [comment]
Added this in release 1.2.3
